development:
  adapter: mysql2
  database: ubersense_launch_academy
  username: ubersense
  password: uberdb!

test:
  adapter: mysql2
  database: ubersense_launch_academy_test
  username:
  password:

